source 'https://github.com/CocoaPods/Specs.git'

target :ARAnalyticsBootstrapiOS do
  platform :ios, '7.0'
  
  pod 'ARAnalytics', :path => '../', :subspecs => ["Criteo"]
end

target "ARAnalyticsiOSTests" do
  
end
